services:
  db:
    container_name: "database"
    image: mysql:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm i && npm run build && npm run migration:run && npm start"
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      DB_HOST: 'db'
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      db:
        condition: service_healthy